#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=39
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=10
  margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
#source "$ITEM_DIR/spotify.sh"
APPLE_MUSIC_EVENT="com.apple.Music.playerInfo"
POPUP_SCRIPT="sketchybar -m --set applemusic.anchor popup.drawing=toggle"

sketchybar --add       event           applemusic_change $APPLE_MUSIC_EVENT     \
           --add       item            applemusic.anchor center                  \
           --set       applemusic.anchor  script="$PLUGIN_DIR/applemusic.sh"    \
                                       click_script="$POPUP_SCRIPT"             \
                                       popup.horizontal=on                      \
                                       popup.align=center                       \
                                       popup.height=120                         \
                                       icon=􁁒                                   \
                                       icon.font="$FONT:Regular:25.0"           \
                                       label.drawing=off                        \
                                       drawing=on                               \
                                       y_offset=2                               \
           --subscribe applemusic.anchor  mouse.entered mouse.exited            \
                                       mouse.exited.global                      \
                                                                                \
           --add       item            applemusic.cover popup.applemusic.anchor \
           --set       applemusic.cover   script="$PLUGIN_DIR/applemusic.sh"    \
                                       label.drawing=off                        \
                                       icon.drawing=off                         \
                                       background.padding_left=12               \
                                       background.padding_right=10              \
                                       background.image.scale=0.15              \
                                       background.image.drawing=on              \
                                       background.drawing=on                    \
                                                                                \
           --add       item            applemusic.title popup.applemusic.anchor \
           --set       applemusic.title   icon.drawing=off                      \
                                       background.padding_left=0                \
                                       background.padding_right=0               \
                                       width=0                                  \
                                       label.font="$FONT:Heavy:14.0"            \
                                       y_offset=40                              \
                                                                                \
           --add       item            applemusic.artist popup.applemusic.anchor\
           --set       applemusic.artist  icon.drawing=off                      \
                                       y_offset=20                              \
                                       background.padding_left=0                \
                                       background.padding_right=0               \
                                       width=0                                  \
                                                                                \
           --add       item            applemusic.album popup.applemusic.anchor \
           --set       applemusic.album   icon.drawing=off                      \
                                       background.padding_left=0                \
                                       background.padding_right=0               \
                                       y_offset=3                               \
                                       width=0                                  \
                                                                                \
           --add       item            applemusic.shuffle popup.applemusic.anchor\
           --set       applemusic.shuffle icon=􀊝                                \
                                       icon.padding_left=5                      \
                                       icon.padding_right=5                     \
                                       icon.color=$BLACK                        \
                                       icon.highlight_color=$MAGENTA            \
                                       label.drawing=off                        \
                                       script="$PLUGIN_DIR/applemusic.sh"       \
                                       y_offset=-30                             \
           --subscribe applemusic.shuffle mouse.clicked                         \
                                                                                \
           --add       item            applemusic.back popup.applemusic.anchor  \
           --set       applemusic.back    icon=􀊎                                \
                                       icon.padding_left=5                      \
                                       icon.padding_right=5                     \
                                       icon.color=$BLACK                        \
                                       script="$PLUGIN_DIR/applemusic.sh"       \
                                       label.drawing=off                        \
                                       y_offset=-30                             \
           --subscribe applemusic.back    mouse.clicked                         \
                                                                                \
           --add       item            applemusic.play popup.applemusic.anchor  \
           --set       applemusic.play    icon=􀊔                                \
                                       background.height=40                     \
                                       background.corner_radius=20              \
                                       width=40                                 \
                                       align=center                             \
                                       background.color=$BLACK                  \
                                       background.border_color=$WHITE           \
                                       background.border_width=0                \
                                       background.drawing=on                    \
                                       icon.padding_left=4                      \
                                       icon.padding_right=5                     \
                                       icon.color=$WHITE                        \
                                       updates=on                               \
                                       label.drawing=off                        \
                                       script="$PLUGIN_DIR/applemusic.sh"       \
                                       y_offset=-30                             \
           --subscribe applemusic.play    mouse.clicked applemusic_change       \
                                                                                \
           --add       item            applemusic.next popup.applemusic.anchor  \
           --set       applemusic.next    icon=􀊐                                \
                                       icon.padding_left=5                      \
                                       icon.padding_right=10                    \
                                       icon.color=$BLACK                        \
                                       label.drawing=off                        \
                                       script="$PLUGIN_DIR/applemusic.sh"       \
                                       y_offset=-30                             \
           --subscribe applemusic.next    mouse.clicked                         \
                                                                                \
           --add       item            applemusic.repeat popup.applemusic.anchor\
           --set       applemusic.repeat  icon=􀊞                                \
                                       icon.highlight_color=$MAGENTA            \
                                       icon.padding_left=5                      \
                                       icon.padding_right=10                    \
                                       icon.color=$BLACK                        \
                                       label.drawing=off                        \
                                       script="$PLUGIN_DIR/applemusic.sh"       \
                                       y_offset=-30                             \
           --subscribe applemusic.repeat  mouse.clicked                         \
                                                                                \
           --add       item            applemusic.spacer popup.applemusic.anchor\
           --set       applemusic.spacer  width=5                               \
                                                                                \
           --add      bracket          applemusic applemusic.shuffle            \
                                               applemusic.back                  \
                                               applemusic.play                  \
                                               applemusic.next                  \
                                               applemusic.repeat                \
           --set      applemusic          background.color=0xfff94c57              \
                                       background.corner_radius=11              \
                                       background.drawing=on                    \
                                       y_offset=-30                             \
                                       drawing=off

# Right


source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/ical.sh"

source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/color-theme.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/bluetooth.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"

source "$ITEM_DIR/cpu.sh"


# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
